# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "a60d244c671aea1b77910da29781c265"
name = "Framify"
handle = "framify"
application_url = "https://jewelry-flu-rj-surf.trycloudflare.com"
embedded = true

[build]
automatically_update_urls_on_dev = true
dev_store_url = "quickstart-df6da22b.myshopify.com"
include_config_on_deploy = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_product_listings,read_products,unauthenticated_read_product_listings,write_products"

[auth]
redirect_urls = [
  "https://jewelry-flu-rj-surf.trycloudflare.com/auth/callback",
  "https://jewelry-flu-rj-surf.trycloudflare.com/auth/shopify/callback",
  "https://jewelry-flu-rj-surf.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2024-01"

[pos]
embedded = false
